overrides:
  '@io-gui/colors': link:../io/packages/colors
  '@io-gui/core': link:../io/packages/core
  '@io-gui/editors': link:../io/packages/editors
  '@io-gui/icons': link:../io/packages/icons
  '@io-gui/inputs': link:../io/packages/inputs
  '@io-gui/layout': link:../io/packages/layout
  '@io-gui/markdown': link:../io/packages/markdown
  '@io-gui/menus': link:../io/packages/menus
  '@io-gui/navigation': link:../io/packages/navigation
  '@io-gui/sliders': link:../io/packages/sliders
  '@io-gui/three': link:../io/packages/three
